version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "13:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 2
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.5
    - 24.2.1
    - 24.3.2
    - 24.3.4
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.1.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  commit-message:
    prefix: chore
- package-ecosystem: npm
  directory: "/website"
  schedule:
    interval: weekly
    day: friday
    time: "13:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 2
  versioning-strategy: increase
  commit-message:
    prefix: chore
